//! Provider-neutral embedding generation trait and implementations.
//!
//! This module defines the EmbeddingProvider trait that abstracts over
//! different embedding backends (FastEmbed, Ollama, OpenAI, etc.) with
//! a unified interface for generating query and passage embeddings.

use engram_domain::EmbeddingSpace;
use engram_runtime::CoreResult;
use serde::{Deserialize, Serialize};

/// Error type for embedding provider failures.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum EmbeddingError {
    /// Provider is unavailable or cannot be initialized.
    ProviderUnavailable { reason: String },

    /// Embedding generation failed.
    EmbeddingFailed { reason: String },

    /// Batch embedding partially failed.
    PartialBatchFailure {
        succeeded: usize,
        failed: usize,
        reason: String,
    },

    /// Input validation failed.
    InvalidInput { reason: String },
}

/// Provider-neutral embedding generation trait.
///
/// This trait abstracts over different embedding backends (FastEmbed, Ollama,
/// OpenAI, etc.) with a unified interface for generating query and passage
/// embeddings. All implementations must provide stable provider and model
/// identifiers, vector dimensions, and embedding space identity.
pub trait EmbeddingProvider: Send + Sync {
    /// Returns the stable provider identifier (e.g., "fastembed", "ollama", "openai").
    fn provider_id(&self) -> &str;

    /// Returns the stable model identifier within the provider (e.g., "BAAI/bge-small-en-v1.5").
    fn model_id(&self) -> &str;

    /// Returns the vector dimensions for this model (e.g., 384).
    fn dimensions(&self) -> u32;

    /// Returns the embedding space identity for this provider/model combination.
    ///
    /// The embedding space uniquely identifies the compatibility class for
    /// embeddings generated by this provider. Two embeddings are compatible
    /// only if they share the same embedding space (provider + model + dimensions
    /// + prompt_profile + normalization).
    fn embedding_space(&self) -> EmbeddingSpace;

    /// Embeds a single query text using the query prompt profile.
    ///
    /// Query embeddings typically use a different prompt prefix than passage
    /// embeddings (e.g., "query:" for BGE models). The provider is responsible
    /// for applying the correct prompt profile.
    fn embed_query(&self, query: &str) -> CoreResult<Vec<f32>>;

    /// Embeds a single passage text using the passage prompt profile.
    ///
    /// Passage embeddings use the standard prompt profile without query-specific
    /// prefixes. This is used to vectorize ingested knowledge chunks for
    /// nearest-neighbor search.
    fn embed_passage(&self, text: &str) -> CoreResult<Vec<f32>>;

    /// Embeds multiple texts in a batch for efficiency.
    ///
    /// Implementations may optimize batch embedding through parallelization
    /// or provider-specific batch APIs. Returns a vector of embeddings in
    /// the same order as the input texts.
    ///
    /// # Errors
    ///
    /// Returns an error if the entire batch fails. Some providers may support
    /// partial batch success — in that case, implementations should return
    /// an EmbeddingError::PartialBatchFailure with details.
    fn embed_batch(&self, texts: &[String]) -> CoreResult<Vec<Vec<f32>>> {
        texts.iter().map(|text| self.embed_passage(text)).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use engram_runtime::CoreError;

    /// Mock embedding provider for testing.
    struct MockEmbeddingProvider {
        provider_id: String,
        model_id: String,
        dimensions: u32,
        prompt_profile: String,
    }

    impl MockEmbeddingProvider {
        fn new() -> Self {
            Self {
                provider_id: "test_provider".to_string(),
                model_id: "test_model".to_string(),
                dimensions: 128,
                prompt_profile: "query".to_string(),
            }
        }
    }

    impl EmbeddingProvider for MockEmbeddingProvider {
        fn provider_id(&self) -> &str {
            &self.provider_id
        }

        fn model_id(&self) -> &str {
            &self.model_id
        }

        fn dimensions(&self) -> u32 {
            self.dimensions
        }

        fn embedding_space(&self) -> EmbeddingSpace {
            EmbeddingSpace::new(
                self.provider_id.clone(),
                self.model_id.clone(),
                self.dimensions,
                self.prompt_profile.clone(),
                None::<String>,
            )
        }

        fn embed_query(&self, query: &str) -> CoreResult<Vec<f32>> {
            if query.is_empty() {
                return Err(CoreError::InvalidRequest {
                    reason: "query cannot be empty".to_string(),
                });
            }
            // Return mock embedding of correct dimension
            Ok(vec![0.0; self.dimensions as usize])
        }

        fn embed_passage(&self, text: &str) -> CoreResult<Vec<f32>> {
            if text.is_empty() {
                return Err(CoreError::InvalidRequest {
                    reason: "text cannot be empty".to_string(),
                });
            }
            // Return mock embedding of correct dimension
            Ok(vec![0.0; self.dimensions as usize])
        }
    }

    #[test]
    fn test_embedding_provider_trait_methods_exist() {
        let provider = MockEmbeddingProvider::new();
        assert_eq!(provider.provider_id(), "test_provider");
        assert_eq!(provider.model_id(), "test_model");
        assert_eq!(provider.dimensions(), 128);
    }

    #[test]
    fn test_embedding_space_identity_generation() {
        let provider = MockEmbeddingProvider::new();
        let space = provider.embedding_space();
        assert_eq!(space.provider, "test_provider");
        assert_eq!(space.model, "test_model");
        assert_eq!(space.dimensions, 128);
        assert_eq!(space.prompt_profile, "query");
        assert_eq!(space.normalization, None);
    }

    #[test]
    fn test_embedding_space_identity_is_consistent() {
        let provider = MockEmbeddingProvider::new();
        let space1 = provider.embedding_space();
        let space2 = provider.embedding_space();
        assert_eq!(space1, space2);
        assert_eq!(space1.identifier(), space2.identifier());
    }

    #[test]
    fn test_embed_query_rejects_empty_query() {
        let provider = MockEmbeddingProvider::new();
        let result = provider.embed_query("");
        assert!(result.is_err());
    }

    #[test]
    fn test_embed_passage_rejects_empty_text() {
        let provider = MockEmbeddingProvider::new();
        let result = provider.embed_passage("");
        assert!(result.is_err());
    }

    #[test]
    fn test_embed_query_returns_correct_dimensions() {
        let provider = MockEmbeddingProvider::new();
        let embedding = provider.embed_query("test query").unwrap();
        assert_eq!(embedding.len(), 128);
    }

    #[test]
    fn test_embed_passage_returns_correct_dimensions() {
        let provider = MockEmbeddingProvider::new();
        let embedding = provider.embed_passage("test passage").unwrap();
        assert_eq!(embedding.len(), 128);
    }

    #[test]
    fn test_embed_batch_processes_multiple_texts() {
        let provider = MockEmbeddingProvider::new();
        let texts = vec![
            "first text".to_string(),
            "second text".to_string(),
            "third text".to_string(),
        ];
        let embeddings = provider.embed_batch(&texts).unwrap();
        assert_eq!(embeddings.len(), 3);
        for embedding in embeddings {
            assert_eq!(embedding.len(), 128);
        }
    }

    #[test]
    fn test_embed_batch_propagates_errors() {
        let provider = MockEmbeddingProvider::new();
        let texts = vec![
            "valid text".to_string(),
            "".to_string(), // empty text causes error
            "another valid".to_string(),
        ];
        let result = provider.embed_batch(&texts);
        assert!(result.is_err());
    }
}
