//! Vector index trait with embedding-space validation.
//!
//! This module defines the VectorIndex trait that extends beyond dimensions
//! to validate embedding space identity (provider + model + dimensions +
//! prompt_profile + normalization) before vector operations.

use engram_domain::{EmbeddingSpace, Id};
use engram_runtime::CoreResult;

/// Vector index with embedding-space validation.
///
/// This trait provides raw vector operations with explicit embedding-space
/// validation. Unlike dimension-only checks, embedding-space validation ensures
/// that query and target embeddings are generated by compatible models with
/// the same prompt profile and normalization settings.
///
/// Implementations must reject insert and search operations when embedding
/// spaces don't match, transitioning capability state to RequiresReindex
/// when the configured space changes.
pub trait VectorIndex: Send + Sync {
    /// Returns the embedding space identity for this index.
    ///
    /// The embedding space uniquely identifies the compatibility class for
    /// vectors stored in this index. All insert and search operations must
    /// validate against this space.
    fn embedding_space(&self) -> &EmbeddingSpace;

    /// Inserts a vector with embedding-space validation.
    ///
    /// # Errors
    ///
    /// Returns `CoreError::InvalidRequest` with `EmbeddingSpaceMismatch` reason
    /// if the vector's embedding space doesn't match the index's expected space.
    ///
    /// # Parameters
    ///
    /// - `target_id`: Unique identifier for the vector target
    /// - `embedding_space`: The embedding space identity for the vector
    /// - `vector`: The vector embedding to insert
    fn insert(
        &self,
        target_id: &Id,
        embedding_space: &EmbeddingSpace,
        vector: Vec<f32>,
    ) -> CoreResult<()>;

    /// Searches for similar vectors with embedding-space validation.
    ///
    /// # Errors
    ///
    /// Returns `CoreError::InvalidRequest` with `EmbeddingSpaceMismatch` reason
    /// if the query embedding space doesn't match the index's expected space.
    ///
    /// # Parameters
    ///
    /// - `query_embedding_space`: The embedding space identity for the query
    /// - `query_vector`: The query vector embedding
    /// - `limit`: Maximum number of results to return
    ///
    /// # Returns
    ///
    /// Vector of `(target_id, score)` tuples sorted by similarity score
    /// in descending order (most similar first).
    fn search(
        &self,
        query_embedding_space: &EmbeddingSpace,
        query_vector: Vec<f32>,
        limit: usize,
    ) -> CoreResult<Vec<(Id, f32)>>;

    /// Deletes a vector target by ID.
    ///
    /// # Parameters
    ///
    /// - `target_id`: Unique identifier for the vector target to delete
    fn delete_target(&self, target_id: &Id) -> CoreResult<()>;

    /// Clears all vectors from the index.
    ///
    /// This is a destructive operation that removes all stored vectors.
    /// Implementations should ensure this operation is atomic where possible.
    fn clear(&self) -> CoreResult<()>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use engram_domain::Id;
    use engram_runtime::CoreError;

    /// Mock vector index for testing.
    struct MockVectorIndex {
        embedding_space: EmbeddingSpace,
    }

    impl MockVectorIndex {
        fn new() -> Self {
            Self {
                embedding_space: EmbeddingSpace::new(
                    "test_provider",
                    "test_model",
                    128,
                    "query",
                    None::<String>,
                ),
            }
        }
    }

    impl VectorIndex for MockVectorIndex {
        fn embedding_space(&self) -> &EmbeddingSpace {
            &self.embedding_space
        }

        fn insert(
            &self,
            _target_id: &Id,
            embedding_space: &EmbeddingSpace,
            vector: Vec<f32>,
        ) -> CoreResult<()> {
            // Validate embedding space matches
            if embedding_space != self.embedding_space() {
                return Err(CoreError::InvalidRequest {
                    reason: "embedding_space_mismatch".to_string(),
                });
            }

            // Validate vector dimensions match embedding space
            if vector.len() != self.embedding_space().dimensions as usize {
                return Err(CoreError::InvalidRequest {
                    reason: "dimension_mismatch".to_string(),
                });
            }

            Ok(())
        }

        fn search(
            &self,
            query_embedding_space: &EmbeddingSpace,
            query_vector: Vec<f32>,
            limit: usize,
        ) -> CoreResult<Vec<(Id, f32)>> {
            // Validate embedding space matches
            if query_embedding_space != self.embedding_space() {
                return Err(CoreError::InvalidRequest {
                    reason: "embedding_space_mismatch".to_string(),
                });
            }

            // Validate vector dimensions match embedding space
            if query_vector.len() != self.embedding_space().dimensions as usize {
                return Err(CoreError::InvalidRequest {
                    reason: "dimension_mismatch".to_string(),
                });
            }

            // Validate limit is positive
            if limit == 0 {
                return Err(CoreError::InvalidRequest {
                    reason: "limit must be positive".to_string(),
                });
            }

            Ok(Vec::new())
        }

        fn delete_target(&self, _target_id: &Id) -> CoreResult<()> {
            Ok(())
        }

        fn clear(&self) -> CoreResult<()> {
            Ok(())
        }
    }

    #[test]
    fn test_vector_index_embedding_space_method() {
        let index = MockVectorIndex::new();
        let space = index.embedding_space();
        assert_eq!(space.provider, "test_provider");
        assert_eq!(space.model, "test_model");
        assert_eq!(space.dimensions, 128);
    }

    #[test]
    fn test_insert_validates_embedding_space() {
        let index = MockVectorIndex::new();
        let target_id = Id::new("test_target").unwrap();

        // Matching embedding space should succeed
        let matching_space = index.embedding_space().clone();
        let vector = vec![0.0; 128];
        let result = index.insert(&target_id, &matching_space, vector);
        assert!(result.is_ok());

        // Mismatched embedding space should fail
        let mismatched_space = EmbeddingSpace::new(
            "different_provider",
            "different_model",
            128,
            "query",
            None::<String>,
        );
        let vector = vec![0.0; 128];
        let result = index.insert(&target_id, &mismatched_space, vector);
        assert!(result.is_err());
        if let Err(CoreError::InvalidRequest { reason }) = result {
            assert_eq!(reason, "embedding_space_mismatch");
        } else {
            panic!("Expected InvalidRequest error");
        }
    }

    #[test]
    fn test_insert_validates_dimensions() {
        let index = MockVectorIndex::new();
        let target_id = Id::new("test_target").unwrap();

        // Correct dimensions should succeed
        let embedding_space = index.embedding_space().clone();
        let vector = vec![0.0; 128];
        let result = index.insert(&target_id, &embedding_space, vector);
        assert!(result.is_ok());

        // Wrong dimensions should fail
        let embedding_space = index.embedding_space().clone();
        let vector = vec![0.0; 256]; // Wrong dimension
        let result = index.insert(&target_id, &embedding_space, vector);
        assert!(result.is_err());
        if let Err(CoreError::InvalidRequest { reason }) = result {
            assert_eq!(reason, "dimension_mismatch");
        } else {
            panic!("Expected InvalidRequest error");
        }
    }

    #[test]
    fn test_search_validates_embedding_space() {
        let index = MockVectorIndex::new();

        // Matching embedding space should succeed
        let matching_space = index.embedding_space().clone();
        let query_vector = vec![0.0; 128];
        let result = index.search(&matching_space, query_vector, 10);
        assert!(result.is_ok());

        // Mismatched embedding space should fail
        let mismatched_space = EmbeddingSpace::new(
            "different_provider",
            "different_model",
            128,
            "query",
            None::<String>,
        );
        let query_vector = vec![0.0; 128];
        let result = index.search(&mismatched_space, query_vector, 10);
        assert!(result.is_err());
        if let Err(CoreError::InvalidRequest { reason }) = result {
            assert_eq!(reason, "embedding_space_mismatch");
        } else {
            panic!("Expected InvalidRequest error");
        }
    }

    #[test]
    fn test_search_validates_query_dimensions() {
        let index = MockVectorIndex::new();

        // Correct dimensions should succeed
        let embedding_space = index.embedding_space().clone();
        let query_vector = vec![0.0; 128];
        let result = index.search(&embedding_space, query_vector, 10);
        assert!(result.is_ok());

        // Wrong dimensions should fail
        let embedding_space = index.embedding_space().clone();
        let query_vector = vec![0.0; 256]; // Wrong dimension
        let result = index.search(&embedding_space, query_vector, 10);
        assert!(result.is_err());
        if let Err(CoreError::InvalidRequest { reason }) = result {
            assert_eq!(reason, "dimension_mismatch");
        } else {
            panic!("Expected InvalidRequest error");
        }
    }

    #[test]
    fn test_search_validates_limit() {
        let index = MockVectorIndex::new();

        // Positive limit should succeed
        let embedding_space = index.embedding_space().clone();
        let query_vector = vec![0.0; 128];
        let result = index.search(&embedding_space, query_vector, 10);
        assert!(result.is_ok());

        // Zero limit should fail
        let embedding_space = index.embedding_space().clone();
        let query_vector = vec![0.0; 128];
        let result = index.search(&embedding_space, query_vector, 0);
        assert!(result.is_err());
    }

    #[test]
    fn test_delete_target_succeeds() {
        let index = MockVectorIndex::new();
        let target_id = Id::new("test_target").unwrap();
        let result = index.delete_target(&target_id);
        assert!(result.is_ok());
    }

    #[test]
    fn test_clear_succeeds() {
        let index = MockVectorIndex::new();
        let result = index.clear();
        assert!(result.is_ok());
    }
}
